export default {
  INCREASE_HOURS: 'INCREASE_HOURS',
  DECREASE_HOURS: 'DECREASE_HOURS',
  INCREASE_MINUTES:'INCREASE_MINUTES',
  DECREASE_MINUTES:'DECREASE_MINUTES',
  SUBMIT_ALARM_TIME:'SUBMIT_ALARM_TIME',
  STOP_SONG:'STOP_SONG',
  SONG_SET:'SONG_SET',
  REPEAT_TRIGGER:'REPEAT_TRIGGER',
  UPLOAD_FILE:'UPLOAD_FILE',
  CREATE_PROJECT:'CREATE_PROJECT',
  PROGRESS:'PROGRESS',
  TRY_SONG:'TRY_SONG'
}
