export default {
  INCREASE_HOURS: 'INCREASE_HOURS',
  DECREASE_HOURS: 'DECREASE_HOURS',
  INCREASE_MINUTES:'INCREASE_MINUTES',
  DECREASE_MINUTES:'DECREASE_MINUTES',
  SUBMIT_ALARM_TIME:'SUBMIT_ALARM_TIME'
}
